### ISSUE TITLE
Content component for 3D viewer (optional)

### ISSUE THREAD

**Issue by ClemensBeck** [slub/dlf-3d-viewers#39]
* [x] content component for 3D viewer (optional)

**Comment by markusweigelt** [comment]
Content component/plugin is implemented.

**Comment by ClemensBeck** [comment]
Is it already available in the live version? Or can you post a screenshot?

**Comment by markusweigelt** [comment]
@ClemensBeck It is currently still an open pull request https://github.com/kitodo/kitodo-presentation/pull/1283 and will be merged in the near future,
