### ISSUE TITLE
Integration Testing Repository in WissKI Cloud 

### ISSUE THREAD

**Issue by ClemensBeck** [slub/dlf-3d-viewers#73]
* [x] @thedworak Integration Testing Repository (and CovHer Repo) in WissKI Cloud, including Update to Drupal 10

**Comment by thedworak** [comment]
Created testing environment with basic stuff working.
URL: https://dfg-repository.wisski.cloud
Credentials sent to Igor and Clemens

**Comment by thedworak** [comment]
Here also were added changes in WissKI images for future instances installation
