### ISSUE TITLE
Model download from 3d-repository.hs-mainz.de redirects to the repository model instead of downloading the model

### ISSUE THREAD

**Issue by markusweigelt** [slub/dlf-3d-viewers#76]
Rendering of https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/59.xml in DFG-Viewer works 

![image](https://github.com/user-attachments/assets/5cd4c66b-cfaa-4a83-95b5-64bb400bd384)

but when I want to download the model the link redirects me to repository to display the content of the model in the browser (see https://3d-repository.hs-mainz.de/sites/default/files/2022-07/MZ_1250_Dom_200507_ZIP/gltf/MZ_1250_Dom_200507.glb)

I think the problem is that the content type of the response is not specified in the header of server response, and the browser assumes that the file is a text file.

In the case of models downloaded from Zenodo (https://zenodo.org/api/files/df31cc16-0a54-4599-89e9-0dd4ada4016d/b5df7cd550f64e818943ad96fff7e902.glb), the content type of the response is "application/octet-stream".

**Comment by thedworak** [comment]
I changed here the href element to blob: but still requesting file by filename will lead to the preview of it. It can be achieved only on server's side configuration how to treat such as files.

**Comment by markusweigelt** [comment]
Exactly, the behavior would then need to be forwarded to the appropriate place at the HSM and fixed.

**Comment by ClemensBeck** [comment]
Jour fixe from 16.10.2024: Daniel can fix it on Mainz Repository, but will persist if you switch to another server, @thedworak will provide documentation, when he will fix it

**Comment by thedworak** [comment]
According to your web-server it's necessary to setup the following:

1. **Apache2**

- Add inside `IfModule` block in file: /etc/apache2/mods-available/mime.conf
`	#Start DFG Viewer settings
	AddType model/gltf gltf
	AddType model/gltf-binary glb	
	AddType model/mtl mtl
	AddType model/obj obj
	AddType model/stl stl
	AddType model/vnd.collada+xml dae
	AddType model/x3d+binary x3d

	AddType application/octet-stream fbx
	AddType application/xml ifc
	AddType application/x-3ds 3ds
	AddType application/zip zip
	AddType application/vnd.rar rar
	AddType application/x-gzip gz tgz
	AddType application/gml+xml gml

	AddType text/plain ply
	AddType text/json json
	AddType text/vnd.abc abc

	AddType chemical/x-xyz xyz	
	#End DFG Viewer settings`

- be sure module is enabled by `a2enmod mime` and `service apache2 reload`
- inside you `VirtualHost` block paste this:
`	<FilesMatch "\.(?i:gltf|glb|mtl|obj|stl|dae|x3d|fbx|ifc|3ds|zip|rar|gz|tgz|gml|ply|json|abc|xyz)$">
		ForceType application/octet-stream
		Header set Content-Disposition attachment
	</FilesMatch>`

2. **Nginx**

- inside your `server` block paste the following:
`location ~* (./?|\gltf|\glb|\mtl|\obj|\stl|\dae|\x3d|\fbx|\ifc|\3ds|\zip|\rar|\gz|\tgz|\gml|\ply|\json|\abc|\xyz)$ {
	types { application/octet-stream (.gltf|.glb|.mtl|.obj|.stl|.dae|.x3d|.fbx|.ifc|.3ds|.zip|.rar|.gz|.tgz|.gml|.ply|.json|.abc|.xyz); }
	default_type application/octet-stream;
}`

**Comment by thedworak** [comment]
The glb files are being downloaded right now in our 3d-repository

**Comment by markusweigelt** [comment]
> According to your web-server it's necessary to setup the following:

Thanks for sharing! In my view, setting the response types isn't relevant for the DFG viewer, but only for the server delivering the models. The DFG viewer is only used to display models from external repositories. Or am I seeing this wrong?

Do you mean that as a note for the repositories? Then maybe it could be provided at an appropriate place in the documentation. It gets lost in the issue.

**Comment by thedworak** [comment]
Updated documentation: https://docs.google.com/document/d/1N3IYk0U0Bc_ShDiKaI2G-l7pjkyTbNwxqHXfitOtgec/edit?tab=t.0
