### ISSUE TITLE
Adjustments of model in the viewer don't save.

### ISSUE THREAD

**Issue by igorbajena** [slub/dlf-3d-viewers#77]
During workshop with students with Porto, we've noticed that changes with made in to viewer (like rotation of object) we cannot save. Before after clicking on 'saving' button we've got notification, that settings were saved. Now it's not showing. After refreshing the page model also went back to its original position.

What we tired the save (model rotated by 90 degrees)
![image](https://github.com/user-attachments/assets/fce0fdf6-93a0-45ef-a515-c9df3bd05bdc)
After refreshing the page:
![image](https://github.com/user-attachments/assets/2b2dd8d9-4488-40a0-ae47-6ec37ed2cdab)

**Comment by thedworak** [comment]
Someone just accidentally deleted the file responsible for storing that data. I just recreated this file and put it to the git.
