### ISSUE TITLE
Resolve Link Construction Issues for DFG 3D-Viewer/WissKI 

### ISSUE THREAD

**Issue by ClemensBeck** [slub/dlf-3d-viewers#91]
* [ ] @markusweigelt Check and resolve Link Construction Issues from WissKI Instance to DFG 3D-Viewer 

Explanation from Igor: 
"We currently create links to the DFG 3D-Viewer in WissKI by ending with ‘&no_cache=1’. Then the model should be displayed in the DFG 3D-Viewer in Dworak Viewer and we have the problem of displaying the wrong model. If we add an additional parameter[ ‘&modelviewer=1](https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/4719.xml&no_cache=1&modelviewer=1)’  then the model is displayed correctly in the Model Viewer (see below).
Model in Dworak Viewer:[ https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/4719.xml&no_cache=1](https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/4719.xml&no_cache=1)
Model in Model Viewer:[ https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/4719.xml&no_cache=1&modelviewer=1](https://3dtest.dfg-viewer.de/viewer?tx_dlf[id]=https://3d-repository.hs-mainz.de/sites/default/files/xml_structure/4719.xml&no_cache=1&modelviewer=1)"

**Comment by ClemensBeck** [comment]
Answer from @markusweigelt 
"Have you already installed our integration repository in your TYPO3 DFG-Viewer instance? https://kitodo.github.io/kitodo-presentation/Developers/Embedded3DViewer.html#setup

When this is done, and the prepared 'dlf_3d_viewer' folder with the viewers (see Installation of Integrations [here](https://github.com/slub/dlf-3d-viewers?tab=readme-ov-file#installation)) exists, the viewers can be accessed via the 'tx_dlf[viewer]' parameter.
See also the 'Configuration' section in the documentation: https://kitodo.github.io/kitodo-presentation/Developers/Embedded3DViewer.html#Embedded%203D%20Viewer%20Configuration
For automatic selection of viewer please see https://kitodo.github.io/kitodo-presentation/Developers/Embedded3DViewer.html#automatic-selection-of-the-viewer"

**Comment by ClemensBeck** [comment]
Problem was/is, that on the test system an old version of the DFG 3D-Viewer is running. @markusweigelt will fix it

**Comment by ClemensBeck** [comment]
@igorbajena can you please test if everything is working with the DFG 3D-Viewer Test System (see instructions here: https://github.com/slub/dlf-3d-viewers/blob/main/README.md#dfg-3d-viewer-test-system)? If you have any questions, Markus or I are at your disposal.

**Comment by igorbajena** [comment]
This issue is related to automatic generation of links in Drupal/WissKI, nt DFG 3D-Viewer itself. I'm plannign to have discussion with Mark Fichtner about this issue.

**Comment by igorbajena** [comment]
All of the past links in the repository to test the instances of DFG 3D-Viewer from 1st phase were corrected. However, the automatic generation of proper links needs to be fixed. While it is not planned to use the repository in the near future, I suggest closing the issue for now and solving it during the work on the WissKI Cloud and its connection to DFG 3D-Viewer.

**Comment by ClemensBeck** [comment]
@igorbajena All right. I will close the issue!
